spring.application.name=hobby-hub

spring.datasource.url=jdbc:postgresql://localhost:5432/hobbyhub_db
spring.datasource.username=hobbyhub_user
spring.datasource.password=hobbyhub_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
