spring.application.name=hobby-hub

spring.datasource.url=jdbc:postgresql://localhost:5432/hobbyhub_db
spring.datasource.username=hobbyhub_user
spring.datasource.password=hobbyhub_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=5c52e622db8649
spring.mail.password=96ba9d62f36ea4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true